insert into Teachers values (getdate(), 'Jaxson', 4000, 35000, 'Haley')
insert into Teachers values (getdate(), 'Lucy', 4000, 40000, 'Espinoza')
insert into Teachers values (getdate(), 'Tyler', 4000, 40000, 'Allen')
insert into Teachers values (getdate(), 'Michael', 4000, 40000, 'Lucero')
insert into Teachers values (getdate(), 'Elisha', 5000, 28000, 'Bradford')
insert into Teachers values (getdate(), 'Brendan', 5000, 28000, 'Boyer')
insert into Teachers values (getdate(), 'Alicia', 5000, 29000, 'Velasquez')
insert into Teachers values (getdate(), 'Marcus', 5000, 42000, 'Gregory')
insert into Teachers values (getdate(), 'Eliana', 5000, 42000, 'Fuentes')
insert into Teachers values (getdate(), 'Laila', 6000, 43000, 'Lester')
insert into Teachers values (getdate(), 'Ciaran', 6000, 75000, 'Chan')
insert into Teachers values (getdate(), 'Dexter', 6500, 65000, 'Cunningham')
insert into Teachers values (getdate(), 'Callan', 6500, 50000, 'Munoz')
insert into Teachers values (getdate(), 'Isla', 7000, 24000, 'Dotson')
insert into Teachers values (getdate(), 'Nannie', 7000, 37000, 'Figueroa')
insert into Teachers values (getdate(), 'Rita', 8000, 46000, 'Baxter')
insert into Teachers values (getdate(), 'Jasmine', 8000, 28000, 'Sanchez')
insert into Teachers values (getdate(), 'Khalil', 9000, 87000, 'Holman')

insert into Groups values ('A100', 4, 4)
insert into Groups values ('A197', 3, 3)
insert into Groups values ('A104', 5, 3)
insert into Groups values ('B305', 2, 3)
insert into Groups values ('B413', 2, 2)
insert into Groups values ('B732', 4, 2)
insert into Groups values ('C112', 5, 2)
insert into Groups values ('C300', 1, 1)
insert into Groups values ('D145', 3, 1)
insert into Groups values ('E113', 3, 1)
insert into Groups values ('F827', 3, 1)

insert into Departments values (350000, 'Literature')
insert into Departments values (575000, 'History and Archeology ')
insert into Departments values (860000, 'Business Administration')
insert into Departments values (290000, 'Finance and Accounting')
insert into Departments values (150000, 'Mechanical Engineering')
insert into Departments values (459000, 'Electrical and Information Engineering')
insert into Departments values (550000, 'Diplomacy and International Studies')
insert into Departments values (550000, 'Journalism & Mass Communication')
insert into Departments values (678000, 'Management Science and Project Planning')

insert into Faculties values('Arts')
insert into Faculties values('Classics')
insert into Faculties values('Economics')
insert into Faculties values('Education')
insert into Faculties values('Engineering')
insert into Faculties values('Graduate Studies')
insert into Faculties values('Humanities')
insert into Faculties values('Law')
insert into Faculties values('Music')
insert into Faculties values('Natural Sciences')
insert into Faculties values('Philosophy')
insert into Faculties values('Political Science')